inherit_from: .rubocop_todo.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true
